export default {
	s3: {
		REGION: 'YOUR_S3_BUCKET_REGION',
		BUCKET: 'YOUR_S3_BUCKET_NAME'
	},
	cognito: {
		REGION: 'YOUR_COGNITO_REGION',
		IDENTITY_POOL_ID: 'YOUR_COGNITO_IDENTITY_POOL_ID',
		USER_POOL_ID: 'YOUR_COGNITO_USER_POOL_ID',
		APP_CLIENT_ID: 'YOUR_COGNITO_APP_CLIENT_ID',
		DOMAIN: 'YOUR_COGNITO_DOMAIN',
		SCOPE: ['email', 'openid'],
		REDIRECT_SIGN_IN: 'YOUR_URL_FOR_SIGN_IN',
		REDIRECT_SIGN_OUT: 'YOUR_URL_FOR_SIGN_IN',
		RESPONSE_TYPE: 'code'
	}
};
